"""Added school_pos and school_out_of in subject Level Positions

Revision ID: 0023e156fbfd
Revises: 7451545dba55
Create Date: 2025-08-07 13:21:31.808441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0023e156fbfd'
down_revision: Union[str, Sequence[str], None] = '7451545dba55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subjects', sa.Column('school_pos', sa.Integer(), nullable=True))
    op.add_column('student_subjects', sa.Column('school_out_of', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_subjects', 'school_out_of')
    op.drop_column('student_subjects', 'school_pos')
    # ### end Alembic commands ###
