"""Adding school ranking

Revision ID: 147947269dcf
Revises: 625f1b853fde
Create Date: 2025-07-24 20:37:09.401051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147947269dcf'
down_revision: Union[str, Sequence[str], None] = '625f1b853fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('school_pos', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('school_out_of', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'school_out_of')
    op.drop_column('results', 'school_pos')
    # ### end Alembic commands ###
