"""Added Exclude from GPA in Exam Subjects

Revision ID: 187b120e4dbe
Revises: 70b191b74899
Create Date: 2025-07-18 17:18:20.360329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187b120e4dbe'
down_revision: Union[str, Sequence[str], None] = '70b191b74899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
