"""Initial tables

Revision ID: 27ee243598fc
Revises: 
Create Date: 2025-07-18 11:40:20.532764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27ee243598fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'display_name')
    op.drop_column('subjects', 'exclude_from_gpa')
    op.drop_column('subjects', 'is_present')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('is_present', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('subjects', sa.Column('exclude_from_gpa', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('subjects', sa.Column('display_name', mysql.VARCHAR(length=30), sa.Computed("(concat(`subject_code`,'-',`subject_short`))", persisted=True), nullable=True))
    # ### end Alembic commands ###
