"""Added Exclude from GPA in Exam Subjects Added More

Revision ID: 31a989df2e64
Revises: 187b120e4dbe
Create Date: 2025-07-18 17:28:41.438656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a989df2e64'
down_revision: Union[str, Sequence[str], None] = '187b120e4dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('exclude_from_gpa', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'exclude_from_gpa')
    # ### end Alembic commands ###
