"""Added Grade in Student Subject and Results

Revision ID: 625f1b853fde
Revises: b6847f9711b4
Create Date: 2025-07-23 00:48:09.848433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625f1b853fde'
down_revision: Union[str, Sequence[str], None] = 'b6847f9711b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('avg_grade', sa.String(length=10), nullable=True))
    op.add_column('student_subjects', sa.Column('subject_grade', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_subjects', 'subject_grade')
    op.drop_column('results', 'avg_grade')
    # ### end Alembic commands ###
