"""Add foreign keys to student_subjects an...

Revision ID: 71203789cfc9
Revises: c4228bfc5734
Create Date: 2025-07-18 15:00:15.371256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '71203789cfc9'
down_revision: Union[str, Sequence[str], None] = 'c4228bfc5734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('centre_number', sa.String(length=10), nullable=True))
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'schools', ['centre_number'], ['centre_number'], ondelete='SET NULL')
    op.drop_column('users', 'school_centre_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school_centre_number', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'schools', ['school_centre_number'], ['centre_number'], ondelete='SET NULL')
    op.drop_column('users', 'centre_number')
    # ### end Alembic commands ###
