"""Added out of For School Types Subject Rankings

Revision ID: 7451545dba55
Revises: 147947269dcf
Create Date: 2025-07-26 00:40:51.900217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7451545dba55'
down_revision: Union[str, Sequence[str], None] = '147947269dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subjects', sa.Column('ward_subject_out_of_gvt', sa.Integer(), nullable=True))
    op.add_column('student_subjects', sa.Column('ward_subject_out_of_pvt', sa.Integer(), nullable=True))
    op.add_column('student_subjects', sa.Column('council_subject_out_of_gvt', sa.Integer(), nullable=True))
    op.add_column('student_subjects', sa.Column('council_subject_out_of_pvt', sa.Integer(), nullable=True))
    op.add_column('student_subjects', sa.Column('region_subject_out_of_gvt', sa.Integer(), nullable=True))
    op.add_column('student_subjects', sa.Column('region_subject_out_of_pvt', sa.Integer(), nullable=True))
    op.drop_column('subjects', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('comment', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('student_subjects', 'region_subject_out_of_pvt')
    op.drop_column('student_subjects', 'region_subject_out_of_gvt')
    op.drop_column('student_subjects', 'council_subject_out_of_pvt')
    op.drop_column('student_subjects', 'council_subject_out_of_gvt')
    op.drop_column('student_subjects', 'ward_subject_out_of_pvt')
    op.drop_column('student_subjects', 'ward_subject_out_of_gvt')
    # ### end Alembic commands ###
