"""Add foreign key constraint to student_subjects

Revision ID: 851e5009d4d8
Revises: 6fb6c74c824d
Create Date: 2025-07-18 14:07:17.356454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '851e5009d4d8'
down_revision: Union[str, Sequence[str], None] = '6fb6c74c824d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('exam_level', sa.Enum('STNA', 'SFNA', 'PSLE', 'FTNA', 'CSEE', 'ACSEE', name='examlevel'), nullable=False))
    op.create_foreign_key(None, 'student_subjects', 'exam_subjects', ['exam_id', 'subject_code'], ['exam_id', 'subject_code'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_exams_ibfk_2'), 'user_exams', type_='foreignkey')
    op.drop_constraint(op.f('user_exams_ibfk_1'), 'user_exams', type_='foreignkey')
    op.create_foreign_key(None, 'user_exams', 'exams', ['exam_id'], ['exam_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_exams', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('school_centre_number', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'users', 'schools', ['school_centre_number'], ['centre_number'], ondelete='SET NULL')
    op.drop_column('users', 'centre_number')
    op.drop_column('users', 'school_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('centre_number', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'school_centre_number')
    op.drop_constraint(None, 'user_exams', type_='foreignkey')
    op.drop_constraint(None, 'user_exams', type_='foreignkey')
    op.create_foreign_key(op.f('user_exams_ibfk_1'), 'user_exams', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_exams_ibfk_2'), 'user_exams', 'exams', ['exam_id'], ['exam_id'])
    op.drop_constraint(None, 'student_subjects', type_='foreignkey')
    op.drop_column('exams', 'exam_level')
    # ### end Alembic commands ###
