"""Dropped All Enum Columns to String Columns with Constraints

Revision ID: 8df87febca3c
Revises: dc6fa5262965
Create Date: 2025-07-21 20:28:34.279232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8df87febca3c'
down_revision: Union[str, Sequence[str], None] = 'dc6fa5262965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'avg_style',
               existing_type=mysql.ENUM('AUTO', 'SEVEN_BEST', 'EIGHT_BEST'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('exams', 'exam_level',
               existing_type=mysql.ENUM('STNA', 'SFNA', 'PSLE', 'FTNA', 'CSEE', 'ACSEE'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('schools', 'school_type',
               existing_type=mysql.ENUM('GOVERNMENT', 'PRIVATE', 'UNKNOWN'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('students', 'sex',
               existing_type=mysql.ENUM('MALE', 'FEMALE', 'OTHER'),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('user_exams', 'role',
               existing_type=mysql.ENUM('VIEWER', 'UPLOADER', 'EXAM_ADMIN'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('USER', 'TEACHER', 'ACADEMIC_MASTER', 'HEAD_OF_SCHOOL', 'WEO', 'DEO', 'REO', 'ADMIN'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('USER', 'TEACHER', 'ACADEMIC_MASTER', 'HEAD_OF_SCHOOL', 'WEO', 'DEO', 'REO', 'ADMIN'),
               existing_nullable=False)
    op.alter_column('user_exams', 'role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('VIEWER', 'UPLOADER', 'EXAM_ADMIN'),
               existing_nullable=False)
    op.alter_column('students', 'sex',
               existing_type=sa.String(length=5),
               type_=mysql.ENUM('MALE', 'FEMALE', 'OTHER'),
               existing_nullable=False)
    op.alter_column('schools', 'school_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('GOVERNMENT', 'PRIVATE', 'UNKNOWN'),
               existing_nullable=False)
    op.alter_column('exams', 'exam_level',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('STNA', 'SFNA', 'PSLE', 'FTNA', 'CSEE', 'ACSEE'),
               existing_nullable=False)
    op.alter_column('exams', 'avg_style',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('AUTO', 'SEVEN_BEST', 'EIGHT_BEST'),
               existing_nullable=False)
    # ### end Alembic commands ###
