"""Aaaddedsubmitted by and Submitted on MArks

Revision ID: b6847f9711b4
Revises: 8df87febca3c
Create Date: 2025-07-22 18:25:33.246808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6847f9711b4'
down_revision: Union[str, Sequence[str], None] = '8df87febca3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mat_school_subject_list')
    op.add_column('student_subjects', sa.Column('submitted_by', sa.String(length=50), nullable=True))
    op.add_column('student_subjects', sa.Column('submitted_on', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_subjects', 'submitted_on')
    op.drop_column('student_subjects', 'submitted_by')
    op.create_table('mat_school_subject_list',
    sa.Column('centre_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('school_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('subject_codes_list', mysql.MEDIUMTEXT(), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
