"""Add foreign key to student_subjects.student_id

Revision ID: dcc34b3f10ac
Revises: 7e78d64627e1
Create Date: 2025-07-18 14:38:57.888115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc34b3f10ac'
down_revision: Union[str, Sequence[str], None] = '7e78d64627e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'student_subjects', 'students', ['student_id'], ['student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_subjects', type_='foreignkey')
    # ### end Alembic commands ###
